[build]
  base = "Client"
  publish = "Client/build"
  command = "CI=false npm run build"

[[redirects]]
  from = "/google-redirect"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
